@startuml Inserer_donnees

title Inserer des donnees
actor "Admin" as Ad
participant Application
participant BDD

activate Ad
activate Application

Ad -> Application : Envoie du fichier .CSV
Application --> Application : Vérification du fichier
alt fichier incorrect
loop tant que fichier incorrect
Ad <-- Application : Demande d'un nouveau fichier
Ad -> Application : Nouveau fichier .CSV
Application --> Application : Vérification du fichier
end

end


alt Aucune base de donnée
Application -> BDD : creation de la BDD
activate BDD
end

Application -> BDD : UPDATE BDD
@enduml