@startuml etudiant_prend_photo
title Prise/import photo étudiant
actor Admin
activate Admin
activate Application
alt saisie mail
     Admin-> Application: Saisie du mail
     Application--> Application : Vérification
else nom ou prénom invalide
     Application--> Admin: Refus
end

Application--> Application : Passage sur l'interface de photographie
Application-->> Admin: Retour vidéo continu de la caméra par défaut

opt changement caméra
     Admin-> Application: Appuyer sur le bouton de choix de caméra
     Application--> Application : Récupération de la liste des caméras
     Application--> Admin: Affichage de la liste des caméras
     Admin-> Application: Appuyer sur une caméra
     Application--> Application : Changement de caméra
     Application--> Admin: Retour vidéo continu de la caméra choisie
end

alt Prise photo
     Admin-> Application: Appuyer sur le bouton de prise de photo
     Application--> Application : Traitement de la photo
else import photo
     Admin-> Application: Appuyer sur le bouton d'importation de photo
     Application--> Application : Importation et traitement de la photo
end
Application--> Admin: Affichage des photos

alt confirmation photo
     Admin-> Application: Appuyer sur le bouton de confirmation
     Application--> Application : Sauvegarde
     Application--> Admin: Confirmation de l'enregistrement
else invalidation
     Admin-> Application: Prendre une autre photo
     Application--> Application : retour vers le début de l'état prise de photo
end
@enduml