@startuml Inserer_donnees

title Inserer des donnees
actor "Admin" as Ad
participant Application
participant BDD

activate Ad
activate Application

Ad -> Application : Envoie du fichier .XLSX
Application --> Application : Vérification du fichier
Application --> BDD : Demande de backup
Application <-- BDD : renvoie l'état actuel de la BDD
Ad <-- Application : creer une sauvegarde la BDD
alt fichier incorrect
loop tant que fichier incorrect
Ad <-- Application : Demande d'un nouveau fichier
Ad -> Application : Nouveau fichier .XLSX
Application --> Application : Vérification du fichier
end

end


alt Aucune base de donnée
Application -> BDD : creation de la BDD
activate BDD
end

Application -> BDD : UPDATE BDD
@enduml