@startuml Diagrame composants
[Caméra]
[Génération de PDF] as pdf
[Lecture de fichier xlsx] as xls
interface driverCamera

(mariadb:jdbc) - [Application]
driverCamera -up- [Application]
driverCamera .down.> [Caméra]
(mariadb:jdbc) .up.> [Docker  mariadb:latest] : 3306
[Application] .up.> pdf
[Application] .right.> xls
@enduml