@startuml classDiagram

Package Camera {
    class Camera_Manager
    class Camera_Panel
}

Package Main {
    class Application
    class GraphicInterface
}

Package Données {
    class BDD_Manager
}

class Application {
    readXlsx()
    generateTrombi()
    generateEmargement()
}

class GraphicInterface {

}


class BDD_Manager {
    importBDD()
    createBDD()
    updateBDD()

    setPreferenceTrombi()
}

class Camera_Manager {
    Camera camera
    chooseCamera()
    takePicture() 
    choosePicture() 
    getAvailableCameras()
}

class Camera_Panel {
    displayFlux()
}

Application *-right- GraphicInterface 
Application *-left- BDD_Manager
Application *-down- Camera_Manager

GraphicInterface *-- Camera_Panel

Camera_Manager -right- Camera_Panel : video flux

@enduml