@startuml classDiagram

class Application {
    ReadXls()
    GenerateTrombi()
}

class Interface {

}

class BDD {
    
}

class BDD_Manager {
    GenerateBDD()
    UpdateBDD()
    ImportBDD()

    SetPreferenceTrombi()
}

class Camera_Manager {
    Camera camera
    ChooseCamera()
    TakePicture() 
    ChoosePicture() 
}

class Camera_Panel {
    afficher_flux()
}

Application *-right- Interface 
Application "1" *-left- "1" BDD_Manager
Application "1" *-down- "1" Camera_Manager

Interface *-- Camera_Panel

Camera_Manager -right- Camera_Panel : flux vidéo
BDD -right-* BDD_Manager

@enduml