@startuml etudiant_prend_photo
title Prise photo étudiant
actor Élève
activate Élève
alt saisie nom et prénom
     Élève-> Application: Saisie du nom et prénom
     Élève-> Application: Appuyer sur le bouton d'identification
     Application--> Application : Vérification
else nom ou prénom invalide
     Application--> Élève: Refus
end

Application--> Application : Passage sur l'interface de photographie
Application--> Élève: Page de prise de photo
Application-->> Élève: Retour vidéo continu

Élève-> Application: Appuyer sur le bouton de prise de photo
Application--> Application : Capture de la photo
Application--> Élève: Affichage de la photo


alt confirmation photo
     Élève-> Application: Appuyer sur le bouton de confirmation
     Application--> Application : Sauvegarde
     Application--> Élève: Confirmation de l'enregistrement
else invalidation
     Élève-> Application: Appuyer sur le bouton de refus
     Application--> Application : retour vers le début de l'état prise de photo
end
@enduml